# Importing required libraries

In [1]:
import pandas as pd
import numpy as np

# Loading the Dataset

In [2]:
df=pd.read_csv("data.csv",encoding="ISO-8859-1")

In [3]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# Access first 5 rows

In [4]:
len(df.columns)

8

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# Access bottom 5 rows

In [6]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# No.of rows and columns

In [7]:
df.shape

(541909, 8)

# Displaying total columns from Dataset

In [8]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

# Getting all columns one by one

In [9]:
for col in df.columns:
    print(col)

InvoiceNo
StockCode
Description
Quantity
InvoiceDate
UnitPrice
CustomerID
Country

# Renaming columns names

In [10]:
d={
    'InvoiceNo':"invoice_num",
    'StockCode':"stock_code",
    'Description':"description",
    'Quantity':"quantity",
    'InvoiceDate':"invoice_date",
    'UnitPrice':"unit_price",
    'CustomerID':"customer_id",
    'Country':"country"

}

In [11]:
df.rename(columns=d,inplace=True)

In [12]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# Data Cleaning

# Checking column types

In [13]:
df.dtypes

invoice_num      object
stock_code       object
description      object
quantity          int64
invoice_date     object
unit_price      float64
customer_id     float64
country          object
dtype: object

# DataFrame Information

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   541909 non-null  object
 1   stock_code    541909 non-null  object
 2   description   540455 non-null  object
 3   quantity      541909 non-null  int64
 4   invoice_date  541909 non-null  object
 5   unit_price    541909 non-null  float64
 6   customer_id   406829 non-null  float64
 7   country       541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

# Checking missing values for each column

In [15]:
df.isnull()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
541904,False,False,False,False,False,False,False,False
541905,False,False,False,False,False,False,False,False
541906,False,False,False,False,False,False,False,False
541907,False,False,False,False,False,False,False,False
541908,False,False,False,False,False,False,False,False

# Checking missing values count on each column

In [16]:
df.isnull().sum()

invoice_num          0
stock_code           0
description       1454
quantity             0
invoice_date         0
unit_price           0
customer_id     135080
country              0
dtype: int64

# Checking missing values count on each column, applying sorting

In [17]:
df.isnull().sum().sort_values()

invoice_num          0
stock_code           0
quantity             0
invoice_date         0
country              0
unit_price           0
description       1454
customer_id     135080
dtype: int64

In [18]:
df.isnull().sum().sort_values(ascending=False)

customer_id     135080
description       1454
stock_code           0
invoice_num          0
quantity             0
invoice_date         0
unit_price           0
country              0
dtype: int64

# Checking type of invoice_date column

In [19]:
df.dtypes

invoice_num      object
stock_code       object
description      object
quantity          int64
invoice_date     object
unit_price      float64
customer_id     float64
country          object
dtype: object

In [20]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

# Converting invoice_date data type into datatime data type

In [21]:
df["invoice_date"]=pd.to_datetime(df.invoice_date,format="%m/%d/%Y %H:%M")

In [22]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Checking type of invoice_date

In [23]:
df.dtypes

invoice_num             object
stock_code              object
description             object
quantity                 int64
invoice_date    datetime64[ns]
unit_price             float64
customer_id            float64
country                 object
dtype: object

# call lower() method

In [24]:
df.description

0          WHITE HANGING HEART T-LIGHT HOLDER
1                         WHITE METAL LANTERN
2              CREAM CUPID HEARTS COAT HANGER
3         KNITTED UNION FLAG HOT WATER BOTTLE
4              RED WOOLLY HOTTIE WHITE HEART.
                         ...
541904            PACK OF 20 SPACEBOY NAPKINS
541905           CHILDREN'S APRON DOLLY GIRL
541906          CHILDRENS CUTLERY DOLLY GIRL
541907        CHILDRENS CUTLERY CIRCUS PARADE
541908          BAKING SET 9 PIECE RETROSPOT
Name: description, Length: 541909, dtype: object

In [25]:
df.description.str.lower()

0          white hanging heart t-light holder
1                         white metal lantern
2              cream cupid hearts coat hanger
3         knitted union flag hot water bottle
4              red woolly hottie white heart.
                         ...
541904            pack of 20 spaceboy napkins
541905           children's apron dolly girl
541906          childrens cutlery dolly girl
541907        childrens cutlery circus parade
541908          baking set 9 piece retrospot
Name: description, Length: 541909, dtype: object

In [26]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [27]:
df["description"]=df.description.str.lower()

In [28]:
df.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Missing values

In [29]:
df.isnull().sum()

invoice_num          0
stock_code           0
description       1454
quantity             0
invoice_date         0
unit_price           0
customer_id     135080
country              0
dtype: int64

In [30]:
df.isnull().sum().sort_values(ascending=False)

customer_id     135080
description       1454
stock_code           0
invoice_num          0
quantity             0
invoice_date         0
unit_price           0
country              0
dtype: int64

In [31]:
df_new=df.dropna()

In [32]:
df_new.isnull().sum()

invoice_num     0
stock_code      0
description     0
quantity        0
invoice_date    0
unit_price      0
customer_id     0
country         0
dtype: int64

In [33]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   406829 non-null  object
 1   stock_code    406829 non-null  object
 2   description   406829 non-null  object
 3   quantity      406829 non-null  int64
 4   invoice_date  406829 non-null  datetime64[ns]
 5   unit_price    406829 non-null  float64
 6   customer_id   406829 non-null  float64
 7   country       406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

# Checking type of cust_id data type

In [34]:
df_new.shape

(406829, 8)

In [35]:
df_new.dtypes

invoice_num             object
stock_code              object
description             object
quantity                 int64
invoice_date    datetime64[ns]
unit_price             float64
customer_id            float64
country                 object
dtype: object

In [36]:
df_new["customer_id"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: customer_id, Length: 406829, dtype: float64

# Converting cust_id float type into integer type

In [37]:
import warnings
warnings.filterwarnings("ignore")

In [38]:
df_new["customer_id"]=df_new["customer_id"].astype("int64")

In [39]:
df_new["customer_id"]

0         17850
1         17850
2         17850
3         17850
4         17850
          ...
541904    12680
541905    12680
541906    12680
541907    12680
541908    12680
Name: customer_id, Length: 406829, dtype: int64

In [40]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_num   406829 non-null  object
 1   stock_code    406829 non-null  object
 2   description   406829 non-null  object
 3   quantity      406829 non-null  int64
 4   invoice_date  406829 non-null  datetime64[ns]
 5   unit_price    406829 non-null  float64
 6   customer_id   406829 non-null  int64
 7   country       406829 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 27.9+ MB

# DataFrame description

In [41]:
df_new.describe()

,quantity,invoice_date,unit_price,customer_id
count,406829.000000,406829,406829.000000,406829.000000
mean,12.061303,2011-07-10 16:30:57.879207424,3.460471,15287.690570
min,-80995.000000,2010-12-01 08:26:00,0.000000,12346.000000
25%,2.000000,2011-04-06 15:02:00,1.250000,13953.000000
50%,5.000000,2011-07-31 11:48:00,1.950000,15152.000000
75%,12.000000,2011-10-20 13:06:00,3.750000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,248.693370,NaN,69.315162,1713.600303

# Removing negative values from quantity column

In [42]:
df_new.quantity>0

0         True
1         True
2         True
3         True
4         True
          ...
541904    True
541905    True
541906    True
541907    True
541908    True
Name: quantity, Length: 406829, dtype: bool

In [43]:
con=df_new.quantity>0

In [44]:
df_new=df_new[con]

In [45]:
df_new.describe().round(2)

        quantity                   invoice_date  unit_price  customer_id
count  397924.00                         397924   397924.00    397924.00
mean       13.02  2011-07-10 23:43:36.912475648        3.12     15294.32
min         1.00            2010-12-01 08:26:00        0.00     12346.00
25%         2.00            2011-04-07 11:12:00        1.25     13969.00
50%         6.00            2011-07-31 14:39:00        1.95     15159.00
75%        12.00            2011-10-20 14:33:00        3.75     16795.00
max     80995.00            2011-12-09 12:50:00     8142.75     18287.00
std       180.42                            NaN       22.10      1713.17

In [46]:
df_new.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [47]:
df_new.shape

(397924, 8)

# Adding the column - amount_spent

In [48]:
df_new["amount_spent"]=df_new["quantity"]*df_new["unit_price"]

In [49]:
df_new.head()

,invoice_num,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,amount_spent
0,536365,85123A,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [50]:
for col in df_new.columns:
    print(col)

invoice_num
stock_code
description
quantity
invoice_date
unit_price
customer_id
country
amount_spent

In [51]:
len(df_new.columns)

9

# Rearranging columns for more readability

In [52]:
col_order=["invoice_num","invoice_date","stock_code","description","quantity","unit_price","amount_spent","customer_id","country"]

In [53]:
df_new=df_new[col_order]

In [54]:
df_new.head()

,invoice_num,invoice_date,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

# Accessing invoice_date column

In [55]:
df_new["invoice_date"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: invoice_date, Length: 397924, dtype: datetime64[ns]

# Accessing year value from invoice_date

In [56]:
df_new["invoice_date"].dt.year

0         2010
1         2010
2         2010
3         2010
4         2010
          ...
541904    2011
541905    2011
541906    2011
541907    2011
541908    2011
Name: invoice_date, Length: 397924, dtype: int32

# Accessing month value from invoice_date

In [57]:
df_new["invoice_date"].dt.month

0         12
1         12
2         12
3         12
4         12
          ..
541904    12
541905    12
541906    12
541907    12
541908    12
Name: invoice_date, Length: 397924, dtype: int32

# Inserting year_month column in 2nd position

In [58]:
c1="year_month"

In [59]:
v1=df_new["invoice_date"].map(lambda col:100*(col.year)+col.month)

In [60]:
df_new.insert(loc=2,column=c1,value=v1)

In [61]:
df_new.head()

,invoice_num,invoice_date,year_month,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

# Inserting month column in 3nd position

In [62]:
c2="month"

In [63]:
v2=df_new["invoice_date"].dt.month

In [64]:
df_new.insert(loc=3,column=c2,value=v2)

In [65]:
df_new.head()

,invoice_num,invoice_date,year_month,month,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

In [66]:
df_new["invoice_date"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: invoice_date, Length: 397924, dtype: datetime64[ns]

# To can get day of the week

In [67]:
df_new["invoice_date"].dt.dayofweek

0         2
1         2
2         2
3         2
4         2
         ..
541904    4
541905    4
541906    4
541907    4
541908    4
Name: invoice_date, Length: 397924, dtype: int32

# Applying +1 to make Monday = 1.....until Sunday = 7

In [68]:
c3="day"

In [69]:
v3=(df_new["invoice_date"].dt.dayofweek)+1

In [70]:
df_new.insert(loc=4,column=c3,value=v3)

In [71]:
df_new.head()

,invoice_num,invoice_date,year_month,month,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,3,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,3,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,3,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,3,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,3,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

# Adding hour column to existing DataFrame

In [72]:
c4="hour"

In [73]:
v4=df_new["invoice_date"].dt.hour

In [74]:
df_new.insert(loc=4,column=c4,value=v4)

In [75]:
df_new.head()

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,8,3,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,8,3,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,8,3,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,8,3,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,8,3,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

In [76]:
df_new.columns

Index(['invoice_num', 'invoice_date', 'year_month', 'month', 'hour', 'day',
       'stock_code', 'description', 'quantity', 'unit_price', 'amount_spent',
       'customer_id', 'country'],
      dtype='object')

In [77]:
for col in df_new.columns:
    print(col)

invoice_num
invoice_date
year_month
month
hour
day
stock_code
description
quantity
unit_price
amount_spent
customer_id
country

In [78]:
df_new.shape

(397924, 13)

In [79]:
df_new.groupby(by=["customer_id"]).count()

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,country
customer_id,,,,,,,,,,,,
12346,1,1,1,1,1,1,1,1,1,1,1,1
12347,182,182,182,182,182,182,182,182,182,182,182,182
12348,31,31,31,31,31,31,31,31,31,31,31,31
12349,73,73,73,73,73,73,73,73,73,73,73,73
12350,17,17,17,17,17,17,17,17,17,17,17,17
...,...,...,...,...,...,...,...,...,...,...,...,...
18280,10,10,10,10,10,10,10,10,10,10,10,10
18281,7,7,7,7,7,7,7,7,7,7,7,7
18282,12,12,12,12,12,12,12,12,12,12,12,12
18283,756,756,756,756,756,756,756,756,756,756,756,756
18287,70,70,70,70,70,70,70,70,70,70,70,70

In [80]:
df_new.groupby(by=["customer_id","country"]).count()

,,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent
customer_id,country,,,,,,,,,,,
12346,United Kingdom,1,1,1,1,1,1,1,1,1,1,1
12347,Iceland,182,182,182,182,182,182,182,182,182,182,182
12348,Finland,31,31,31,31,31,31,31,31,31,31,31
12349,Italy,73,73,73,73,73,73,73,73,73,73,73
12350,Norway,17,17,17,17,17,17,17,17,17,17,17
...,...,...,...,...,...,...,...,...,...,...,...,...
18280,United Kingdom,10,10,10,10,10,10,10,10,10,10,10
18281,United Kingdom,7,7,7,7,7,7,7,7,7,7,7
18282,United Kingdom,12,12,12,12,12,12,12,12,12,12,12
18283,United Kingdom,756,756,756,756,756,756,756,756,756,756,756
18287,United Kingdom,70,70,70,70,70,70,70,70,70,70,70

In [81]:
df_new.groupby(by=["customer_id","country"])["invoice_num"].count()

customer_id  country
12346        United Kingdom      1
12347        Iceland           182
12348        Finland            31
12349        Italy              73
12350        Norway             17
                              ...
18280        United Kingdom     10
18281        United Kingdom      7
18282        United Kingdom     12
18283        United Kingdom    756
18287        United Kingdom     70
Name: invoice_num, Length: 4347, dtype: int64

In [82]:
df_new.groupby(by=["customer_id","country"],as_index=False)["invoice_num"].count()

      customer_id         country  invoice_num
0           12346  United Kingdom            1
1           12347         Iceland          182
2           12348         Finland           31
3           12349           Italy           73
4           12350          Norway           17
...           ...             ...          ...
4342        18280  United Kingdom           10
4343        18281  United Kingdom            7
4344        18282  United Kingdom           12
4345        18283  United Kingdom          756
4346        18287  United Kingdom           70

[4347 rows x 3 columns]

In [83]:
df_new.groupby(by=["customer_id","country"],as_index=False)["invoice_num"].count().head()

   customer_id         country  invoice_num
0        12346  United Kingdom            1
1        12347         Iceland          182
2        12348         Finland           31
3        12349           Italy           73
4        12350          Norway           17

In [84]:
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (3.10.0)

[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: contourpy>=1.0.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.1)
Requirement already satisfied: packaging>=20.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [85]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.1)
Requirement already satisfied: pandas>=1.2 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\harik\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [86]:
import matplotlib.pyplot as plt
import seaborn as sns

In [87]:
df_new.groupby(by=["customer_id","country"],as_index=False)["invoice_num"].count()

      customer_id         country  invoice_num
0           12346  United Kingdom            1
1           12347         Iceland          182
2           12348         Finland           31
3           12349           Italy           73
4           12350          Norway           17
...           ...             ...          ...
4342        18280  United Kingdom           10
4343        18281  United Kingdom            7
4344        18282  United Kingdom           12
4345        18283  United Kingdom          756
4346        18287  United Kingdom           70

[4347 rows x 3 columns]

In [88]:
orders=df_new.groupby(by=["customer_id","country"],as_index=False)["invoice_num"].count()

In [89]:
orders

      customer_id         country  invoice_num
0           12346  United Kingdom            1
1           12347         Iceland          182
2           12348         Finland           31
3           12349           Italy           73
4           12350          Norway           17
...           ...             ...          ...
4342        18280  United Kingdom           10
4343        18281  United Kingdom            7
4344        18282  United Kingdom           12
4345        18283  United Kingdom          756
4346        18287  United Kingdom           70

[4347 rows x 3 columns]

In [90]:
orders.sort_values(by=["invoice_num"],ascending=False).head()

      customer_id         country  invoice_num
4019        17841  United Kingdom         7847
1888        14911            EIRE         5677
1298        14096  United Kingdom         5111
334         12748  United Kingdom         4596
1670        14606  United Kingdom         2700

# How much money spent by each customers

In [91]:
df_new.groupby(by=["customer_id","country"])["amount_spent"].sum()

customer_id  country
12346        United Kingdom    77183.60
12347        Iceland            4310.00
12348        Finland            1797.24
12349        Italy              1757.55
12350        Norway              334.40
                                 ...
18280        United Kingdom      180.60
18281        United Kingdom       80.82
18282        United Kingdom      178.05
18283        United Kingdom     2094.88
18287        United Kingdom     1837.28
Name: amount_spent, Length: 4347, dtype: float64

In [92]:
df_new.groupby(by=["customer_id","country"],as_index=False)["amount_spent"].sum()

      customer_id         country  amount_spent
0           12346  United Kingdom      77183.60
1           12347         Iceland       4310.00
2           12348         Finland       1797.24
3           12349           Italy       1757.55
4           12350          Norway        334.40
...           ...             ...           ...
4342        18280  United Kingdom        180.60
4343        18281  United Kingdom         80.82
4344        18282  United Kingdom        178.05
4345        18283  United Kingdom       2094.88
4346        18287  United Kingdom       1837.28

[4347 rows x 3 columns]

In [93]:
money_spent=df_new.groupby(by=["customer_id","country"],as_index=False)["amount_spent"].sum()

In [94]:
money_spent

      customer_id         country  amount_spent
0           12346  United Kingdom      77183.60
1           12347         Iceland       4310.00
2           12348         Finland       1797.24
3           12349           Italy       1757.55
4           12350          Norway        334.40
...           ...             ...           ...
4342        18280  United Kingdom        180.60
4343        18281  United Kingdom         80.82
4344        18282  United Kingdom        178.05
4345        18283  United Kingdom       2094.88
4346        18287  United Kingdom       1837.28

[4347 rows x 3 columns]

In [95]:
money_spent.sort_values(by=["amount_spent"])

      customer_id         country  amount_spent
693         13256  United Kingdom          0.00
3226        16738  United Kingdom          3.75
1802        14792  United Kingdom          6.20
3023        16454  United Kingdom          6.90
4107        17956  United Kingdom         12.75
...           ...             ...           ...
1888        14911            EIRE     143825.06
3017        16446  United Kingdom     168472.50
3737        17450  United Kingdom     194550.79
4210        18102  United Kingdom     259657.30
1698        14646     Netherlands     280206.02

[4347 rows x 3 columns]

# Top FIVE customers who spend highest money

In [96]:
money_spent.sort_values(by=["amount_spent"],ascending=False).head()

      customer_id         country  amount_spent
1698        14646     Netherlands     280206.02
4210        18102  United Kingdom     259657.30
3737        17450  United Kingdom     194550.79
3017        16446  United Kingdom     168472.50
1888        14911            EIRE     143825.06

# Top TEN customers who spend highest money

In [97]:
money_spent.sort_values(by=["amount_spent"],ascending=False).head(10)

      customer_id         country  amount_spent
1698        14646     Netherlands     280206.02
4210        18102  United Kingdom     259657.30
3737        17450  United Kingdom     194550.79
3017        16446  United Kingdom     168472.50
1888        14911            EIRE     143825.06
57          12415       Australia     124914.53
1342        14156            EIRE     117379.63
3780        17511  United Kingdom      91062.38
2711        16029  United Kingdom      81024.84
0           12346  United Kingdom      77183.60

In [98]:
df_new.head()

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,8,3,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,8,3,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,8,3,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,8,3,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,8,3,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

# No.of orders for different months

In [99]:
df_new.groupby("invoice_num")

In [100]:
df_new.groupby("invoice_num")["year_month"]

In [101]:
df_new.groupby("invoice_num")["year_month"].unique()

invoice_num
536365    [201012]
536366    [201012]
536367    [201012]
536368    [201012]
536369    [201012]
            ...
581583    [201112]
581584    [201112]
581585    [201112]
581586    [201112]
581587    [201112]
Name: year_month, Length: 18536, dtype: object

In [102]:
df_new.groupby("invoice_num")["year_month"].unique().value_counts()

year_month
[201111]    2658
[201110]    1929
[201109]    1756
[201105]    1555
[201012]    1400
[201106]    1393
[201107]    1331
[201103]    1321
[201108]    1281
[201104]    1149
[201102]     998
[201101]     987
[201112]     778
Name: count, dtype: int64

In [103]:
df_new.groupby("invoice_num")["year_month"].unique().value_counts().sort_index()

year_month
[201012]    1400
[201101]     987
[201102]     998
[201103]    1321
[201104]    1149
[201105]    1555
[201106]    1393
[201107]    1331
[201108]    1281
[201109]    1756
[201110]    1929
[201111]    2658
[201112]     778
Name: count, dtype: int64

# orders per day

In [104]:
df_new.groupby("invoice_num")

In [105]:
df_new.groupby("invoice_num")["day"]

In [106]:
df_new.groupby("invoice_num")["day"].unique()

invoice_num
536365    [3]
536366    [3]
536367    [3]
536368    [3]
536369    [3]
         ...
581583    [5]
581584    [5]
581585    [5]
581586    [5]
581587    [5]
Name: day, Length: 18536, dtype: object

In [107]:
df_new.groupby("invoice_num")["day"].unique().value_counts()

day
[4]    4033
[3]    3455
[2]    3185
[1]    2863
[5]    2831
[7]    2169
Name: count, dtype: int64

In [108]:
df_new.groupby("invoice_num")["day"].unique().value_counts().sort_index()

day
[1]    2863
[2]    3185
[3]    3455
[4]    4033
[5]    2831
[7]    2169
Name: count, dtype: int64

In [109]:
df_new.head()

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,8,3,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,8,3,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,8,3,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,8,3,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,8,3,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom

# Discovering patterns for Unit Price

In [110]:
df_new.unit_price.describe()

count    397924.000000
mean          3.116174
std          22.096788
min           0.000000
25%           1.250000
50%           1.950000
75%           3.750000
max        8142.750000
Name: unit_price, dtype: float64

In [111]:
df_free=df_new[df_new.unit_price==0]

In [112]:
df_free

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
9302,537197,2010-12-05 14:02:00,201012,12,14,7,22841,round cake tin vintage green,1,0.0,0.0,12647,Germany
33576,539263,2010-12-16 14:36:00,201012,12,14,4,22580,advent calendar gingham sack,4,0.0,0.0,16560,United Kingdom
40089,539722,2010-12-21 13:45:00,201012,12,13,2,22423,regency cakestand 3 tier,10,0.0,0.0,14911,EIRE
47068,540372,2011-01-06 16:41:00,201101,1,16,4,22090,paper bunting retrospot,24,0.0,0.0,13081,United Kingdom
47070,540372,2011-01-06 16:41:00,201101,1,16,4,22553,plasters in tin skulls,24,0.0,0.0,13081,United Kingdom
56674,541109,2011-01-13 15:10:00,201101,1,15,4,22168,organiser wood antique white,1,0.0,0.0,15107,United Kingdom
86789,543599,2011-02-10 13:08:00,201102,2,13,4,84535B,fairy cakes notebook a6 size,16,0.0,0.0,17560,United Kingdom
130188,547417,2011-03-23 10:25:00,201103,3,10,3,22062,ceramic bowl with love heart design,36,0.0,0.0,13239,United Kingdom
139453,548318,2011-03-30 12:45:00,201103,3,12,3,22055,mini cake stand hanging strawbery,5,0.0,0.0,13113,United Kingdom
145208,548871,2011-04-04 14:42:00,201104,4,14,1,22162,heart garland rustic padded,2,0.0,0.0,14410,United Kingdom
157042,550188,2011-04-14 18:57:00,201104,4,18,4,22636,childs breakfast set circus parade,1,0.0,0.0,12457,Switzerland
187613,553000,2011-05-12 15:21:00,201105,5,15,4,47566,party bunting,4,0.0,0.0,17667,United Kingdom
198383,554037,2011-05-20 14:13:00,201105,5,14,5,22619,set of 6 soldier skittles,80,0.0,0.0,12415,Australia
279324,561284,2011-07-26 12:24:00,201107,7,12,2,22167,oval wall mirror diamante,1,0.0,0.0,16818,United Kingdom
282912,561669,2011-07-28 17:09:00,201107,7,17,4,22960,jam making set with jars,11,0.0,0.0,12507,Spain
285657,561916,2011-08-01 11:44:00,201108,8,11,1,M,manual,1,0.0,0.0,15581,United Kingdom
298054,562973,2011-08-11 11:42:00,201108,8,11,4,23157,set of 6 nativity magnets,240,0.0,0.0,14911,EIRE
314745,564651,2011-08-26 14:19:00,201108,8,14,5,23270,set of 2 ceramic painted hearts,96,0.0,0.0,14646,Netherlands
314746,564651,2011-08-26 14:19:00,201108,8,14,5,23268,set of 2 ceramic christmas reindeer,192,0.0,0.0,14646,Netherlands
314747,564651,2011-08-26 14:19:00,201108,8,14,5,22955,36 foil star cake cases,144,0.0,0.0,14646,Netherlands
314748,564651,2011-08-26 14:19:00,201108,8,14,5,21786,polkadot rain hat,144,0.0,0.0,14646,Netherlands
358655,568158,2011-09-25 12:22:00,201109,9,12,7,PADS,pads to match all cushions,1,0.0,0.0,16133,United Kingdom
361825,568384,2011-09-27 09:46:00,201109,9,9,2,M,manual,1,0.0,0.0,12748,United Kingdom
379913,569716,2011-10-06 08:17:00,201110,10,8,4,22778,glass cloche small,2,0.0,0.0,15804,United Kingdom
395529,571035,2011-10-13 12:50:00,201110,10,12,4,M,manual,1,0.0,0.0,12446,RSA
420404,572893,2011-10-26 14:36:00,201110,10,14,3,21208,pastel colour honeycomb fan,5,0.0,0.0,18059,United Kingdom
436428,574138,2011-11-03 11:26:00,201111,11,11,4,23234,biscuit tin vintage christmas,216,0.0,0.0,12415,Australia
436597,574175,2011-11-03 11:47:00,201111,11,11,4,22065,christmas pudding trinket pot,12,0.0,0.0,14110,United Kingdom
436961,574252,2011-11-03 13:24:00,201111,11,13,4,M,manual,1,0.0,0.0,12437,France
439361,574469,2011-11-04 11:55:00,201111,11,11,5,22385,jumbo bag spaceboy design,12,0.0,0.0,12431,Australia
446125,574879,2011-11-07 13:22:00,201111,11,13,1,22625,red kitchen scales,2,0.0,0.0,13014,United Kingdom
446793,574920,2011-11-07 16:34:00,201111,11,16,1,22899,children's apron dolly girl,1,0.0,0.0,13985,United Kingdom
446794,574920,2011-11-07 16:34:00,201111,11,16,1,23480,mini lights woodland mushrooms,1,0.0,0.0,13985,United Kingdom
454463,575579,2011-11-10 11:49:00,201111,11,11,4,22437,set of 9 black skull balloons,20,0.0,0.0,13081,United Kingdom
454464,575579,2011-11-10 11:49:00,201111,11,11,4,22089,paper bunting vintage paisley,24,0.0,0.0,13081,United Kingdom
479079,577129,2011-11-17 19:52:00,201111,11,19,4,22464,hanging metal heart lantern,4,0.0,0.0,15602,United Kingdom
479546,577168,2011-11-18 10:42:00,201111,11,10,5,M,manual,1,0.0,0.0,12603,Germany
480649,577314,2011-11-18 13:23:00,201111,11,13,5,23407,set of 2 trays home sweet home,2,0.0,0.0,12444,Norway
485985,577696,2011-11-21 11:57:00,201111,11,11,1,M,manual,1,0.0,0.0,16406,United Kingdom
502122,578841,2011-11-25 15:57:00,201111,11,15,5,84826,asstd design 3d paper stickers,12540,0.0,0.0,13256,United Kingdom

In [113]:
len(df_free)

40

In [114]:
df_free.year_month

9302      201012
33576     201012
40089     201012
47068     201101
47070     201101
56674     201101
86789     201102
130188    201103
139453    201103
145208    201104
157042    201104
187613    201105
198383    201105
279324    201107
282912    201107
285657    201108
298054    201108
314745    201108
314746    201108
314747    201108
314748    201108
358655    201109
361825    201109
379913    201110
395529    201110
420404    201110
436428    201111
436597    201111
436961    201111
439361    201111
446125    201111
446793    201111
446794    201111
454463    201111
454464    201111
479079    201111
479546    201111
480649    201111
485985    201111
502122    201111
Name: year_month, dtype: int64

In [115]:
df_free.year_month.value_counts()

year_month
201111    14
201108     6
201012     3
201110     3
201101     3
201107     2
201103     2
201104     2
201105     2
201109     2
201102     1
Name: count, dtype: int64

In [116]:
df_new.year_month.value_counts().sort_values()

year_month
201112    17304
201102    19928
201101    21232
201104    22644
201012    26160
201107    26827
201108    27013
201103    27177
201106    27185
201105    28322
201109    40030
201110    49557
201111    64545
Name: count, dtype: int64

# No.of orders for each country

In [117]:
df_new

,invoice_num,invoice_date,year_month,month,hour,day,stock_code,description,quantity,unit_price,amount_spent,customer_id,country
0,536365,2010-12-01 08:26:00,201012,12,8,3,85123A,white hanging heart t-light holder,6,2.55,15.30,17850,United Kingdom
1,536365,2010-12-01 08:26:00,201012,12,8,3,71053,white metal lantern,6,3.39,20.34,17850,United Kingdom
2,536365,2010-12-01 08:26:00,201012,12,8,3,84406B,cream cupid hearts coat hanger,8,2.75,22.00,17850,United Kingdom
3,536365,2010-12-01 08:26:00,201012,12,8,3,84029G,knitted union flag hot water bottle,6,3.39,20.34,17850,United Kingdom
4,536365,2010-12-01 08:26:00,201012,12,8,3,84029E,red woolly hottie white heart.,6,3.39,20.34,17850,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,2011-12-09 12:50:00,201112,12,12,5,22613,pack of 20 spaceboy napkins,12,0.85,10.20,12680,France
541905,581587,2011-12-09 12:50:00,201112,12,12,5,22899,children's apron dolly girl,6,2.10,12.60,12680,France
541906,581587,2011-12-09 12:50:00,201112,12,12,5,23254,childrens cutlery dolly girl,4,4.15,16.60,12680,France
541907,581587,2011-12-09 12:50:00,201112,12,12,5,23255,childrens cutlery circus parade,4,4.15,16.60,12680,France
541908,581587,2011-12-09 12:50:00,201112,12,12,5,22138,baking set 9 piece retrospot,3,4.95,14.85,12680,France

In [118]:
df_new.groupby("country")

In [119]:
df_new.groupby("country")["invoice_num"]

In [120]:
df_new.groupby("country")["invoice_num"].count()

country
Australia                 1185
Austria                    398
Bahrain                     17
Belgium                   2031
Brazil                      32
Canada                     151
Channel Islands            748
Cyprus                     614
Czech Republic              25
Denmark                    380
EIRE                      7238
European Community          60
Finland                    685
France                    8342
Germany                   9042
Greece                     145
Iceland                    182
Israel                     248
Italy                      758
Japan                      321
Lebanon                     45
Lithuania                   35
Malta                      112
Netherlands               2363
Norway                    1072
Poland                     330
Portugal                  1462
RSA                         58
Saudi Arabia                 9
Singapore                  222
Spain                     2485
Sweden                     451
Switzerland               1842
USA                        179
United Arab Emirates        68
United Kingdom          354345
Unspecified                244
Name: invoice_num, dtype: int64

In [121]:
df_new.groupby("country")["invoice_num"].count().sort_values()

country
Saudi Arabia                 9
Bahrain                     17
Czech Republic              25
Brazil                      32
Lithuania                   35
Lebanon                     45
RSA                         58
European Community          60
United Arab Emirates        68
Malta                      112
Greece                     145
Canada                     151
USA                        179
Iceland                    182
Singapore                  222
Unspecified                244
Israel                     248
Japan                      321
Poland                     330
Denmark                    380
Austria                    398
Sweden                     451
Cyprus                     614
Finland                    685
Channel Islands            748
Italy                      758
Norway                    1072
Australia                 1185
Portugal                  1462
Switzerland               1842
Belgium                   2031
Netherlands               2363
Spain                     2485
EIRE                      7238
France                    8342
Germany                   9042
United Kingdom          354345
Name: invoice_num, dtype: int64

# Money spent by each country

In [122]:
df_new.groupby("country")

In [123]:
df_new.groupby("country")["amount_spent"]

In [124]:
df_new.groupby("country")["amount_spent"].sum()

country
Australia                138521.310
Austria                   10198.680
Bahrain                     548.400
Belgium                   41196.340
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20450.440
Cyprus                    13590.380
Czech Republic              826.740
Denmark                   18955.340
EIRE                     265545.900
European Community         1300.250
Finland                   22546.080
France                   209024.050
Germany                  228867.140
Greece                     4760.520
Iceland                    4310.000
Israel                     7221.690
Italy                     17483.240
Japan                     37416.370
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2725.590
Netherlands              285446.340
Norway                    36165.440
Poland                     7334.650
Portugal                  33439.890
RSA                        1002.310
Saudi Arabia                145.920
Singapore                 21279.290
Spain                     61577.110
Sweden                    38378.330
Switzerland               56443.950
USA                        3580.390
United Arab Emirates       1902.280
United Kingdom          7308391.554
Unspecified                2667.070
Name: amount_spent, dtype: float64

In [125]:
df_new.groupby("country")["amount_spent"].sum().sort_values()

country
Saudi Arabia                145.920
Bahrain                     548.400
Czech Republic              826.740
RSA                        1002.310
Brazil                     1143.600
European Community         1300.250
Lithuania                  1661.060
Lebanon                    1693.880
United Arab Emirates       1902.280
Unspecified                2667.070
Malta                      2725.590
USA                        3580.390
Canada                     3666.380
Iceland                    4310.000
Greece                     4760.520
Israel                     7221.690
Poland                     7334.650
Austria                   10198.680
Cyprus                    13590.380
Italy                     17483.240
Denmark                   18955.340
Channel Islands           20450.440
Singapore                 21279.290
Finland                   22546.080
Portugal                  33439.890
Norway                    36165.440
Japan                     37416.370
Sweden                    38378.330
Belgium                   41196.340
Switzerland               56443.950
Spain                     61577.110
Australia                138521.310
France                   209024.050
Germany                  228867.140
EIRE                     265545.900
Netherlands              285446.340
United Kingdom          7308391.554
Name: amount_spent, dtype: float64